/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg7_ingriddominguez;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1234
 */
public class Main_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Main_Principal
     */
    public Main_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombreCajero = new javax.swing.JTextField();
        btn_guardarCajero = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_productos = new javax.swing.JButton();
        tf_nombreProductos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_precioProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_tiempoProducto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombreCliente = new javax.swing.JTextField();
        btn_CrearCliente = new javax.swing.JButton();
        tf_edadCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_realizarCompra = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jcb_productos = new javax.swing.JComboBox<>();
        btn_productosAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcb_cajeros = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel3.setText("Nombre");

        btn_guardarCajero.setText("Crear");
        btn_guardarCajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarCajeroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardarCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btn_guardarCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Creacion de Cajeros", jPanel1);

        jLabel1.setText("Nombre");

        btn_productos.setText("Guardar");
        btn_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_productosMouseClicked(evt);
            }
        });

        jLabel2.setText("Precio");

        jLabel4.setText("Tiempo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btn_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nombreProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tiempoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tiempoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btn_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jTabbedPane1.addTab("Creacion de Productos", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Nombre Cliente");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 99, 25));
        jPanel3.add(tf_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 47, 240, 31));

        btn_CrearCliente.setText("Crear Cliete");
        btn_CrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CrearClienteMouseClicked(evt);
            }
        });
        jPanel3.add(btn_CrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 47, 117, 31));
        jPanel3.add(tf_edadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 96, 240, 31));

        jLabel6.setText("Edad Cliente");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 99, 99, 25));

        btn_realizarCompra.setText("Realizar Compra");
        btn_realizarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_realizarCompraMouseClicked(evt);
            }
        });
        btn_realizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_realizarCompraActionPerformed(evt);
            }
        });
        jPanel3.add(btn_realizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 117, 33));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 560, 120));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setText("Productos");

        btn_productosAgregar.setText("Agregar Producto");
        btn_productosAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_productosAgregarMouseClicked(evt);
            }
        });

        jLabel8.setText("Cajero");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jcb_cajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jcb_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btn_productosAgregar)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_productosAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_cajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jTabbedPane1.addTab("Ventas", jPanel3);

        jButton4.setText("Abrir");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Guardar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Archivo", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarCajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarCajeroMouseClicked
        // TODO add your handling code here:
        try {
            cajero nuevo = new cajero(tf_nombreCajero.getText(), cont);
            cont++;

            //todo.add(nuevo);
            DefaultComboBoxModel model = (DefaultComboBoxModel) jcb_cajeros.getModel();
            model.addElement(nuevo);
            jcb_cajeros.setModel(model);

            JOptionPane.showMessageDialog(this, "Cajero Creado Exitosamente!");
            System.out.println(nuevo.toString());
            tf_nombreCajero.setText("");

            //////////////
            Ventana ventanaTemp = nuevo.getFrame();

            ventanaTemp.setVisible(true);
            // ventanaTemp.pack();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error! Datos no guardados");
        }


    }//GEN-LAST:event_btn_guardarCajeroMouseClicked

    private void btn_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productosMouseClicked
        // TODO add your handling code here:
        try {
            producto nuevo = new producto(tf_nombreProductos.getText(), Double.parseDouble(tf_precioProducto.getText()),
                    Integer.parseInt(tf_tiempoProducto.getText()));

            DefaultComboBoxModel model = (DefaultComboBoxModel) jcb_productos.getModel();
            model.addElement(nuevo);
            jcb_productos.setModel(model);
            todosLosProductos.add(nuevo);
            todo.add(nuevo);
            JOptionPane.showMessageDialog(this, "Producto Creado Exitosamente!");
            System.out.println(nuevo.toString());
            tf_nombreProductos.setText("");
            tf_precioProducto.setText("");
            tf_tiempoProducto.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error! Datos no guardados");
        }

    }//GEN-LAST:event_btn_productosMouseClicked

    private void btn_CrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CrearClienteMouseClicked
        // TODO add your handling code here:
        try {
            cliente nuevo = new cliente(tf_nombreCliente.getText(), Integer.parseInt(tf_edadCliente.getText()));
            //todo.add(nuevo);

            productos = new ArrayList();

            actualCliente = nuevo;
            tf_nombreCliente.setEnabled(false);
            tf_edadCliente.setEnabled(false);
            btn_CrearCliente.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Cliente Creado Exitosamente!");
            System.out.println(nuevo.toString());
            /*tf_nombreCliente.setText("");
            tf_edadCliente.setText("");*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error! Datos no guardados");
        }

    }//GEN-LAST:event_btn_CrearClienteMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        tf_nombreCliente.setText("");
        tf_edadCliente.setText("");
        tf_nombreCliente.setEnabled(true);
        tf_edadCliente.setEnabled(true);
        btn_CrearCliente.setEnabled(true);

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btn_productosAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productosAgregarMouseClicked
        // TODO add your handling code here:
        try {
            producto nuevo = (producto) jcb_productos.getSelectedItem();
            productos.add(nuevo);

            JOptionPane.showMessageDialog(this, "Producto Agregado");
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_productosAgregarMouseClicked

    private void btn_realizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_realizarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_realizarCompraActionPerformed

    private void btn_realizarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_realizarCompraMouseClicked
        // TODO add your handling code here:
        try {
            orden laorden = new orden(((cajero) jcb_cajeros.getSelectedItem()), actualCliente);
            actualCliente.setOrden(laorden);

            laorden.setProductos(productos);

            cajero cajeroActual = (cajero) jcb_cajeros.getSelectedItem();
            cajeroActual.getOrdenes().add(laorden);

            cajeroActual.setOrdenX(laorden);
            cajeroActual.setSeguir();
            Thread proceso = new Thread(cajeroActual);
            proceso.start();

            if (!todo.contains(cajeroActual)) {
                todo.add(cajeroActual);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_realizarCompraMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:

        try {
            JFileChooser jfc = new JFileChooser();
            int seleccion = jfc.showSaveDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                administrarArchivos aA = new administrarArchivos(jfc.getSelectedFile().getPath() + ".idm");
                aA.cargarArchivo();
                aA.setElementos(todosLosProductos);
                aA.escribirArchivo();

                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente!");
                System.out.println("guarde " + aA.getElementos().size());
            }// fin del if

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        try {

            try {
                JFileChooser jfc = new JFileChooser();
                int seleccion = jfc.showOpenDialog(this);
                if (seleccion == JFileChooser.APPROVE_OPTION) {
                    administrarArchivos aA = new administrarArchivos(jfc.getSelectedFile().getPath());
                    aA.cargarArchivo();

                    todosLosProductos = aA.getElementos();
                    
                    DefaultComboBoxModel model = new DefaultComboBoxModel();
                    for (int i = 0; i < todosLosProductos.size(); i++) {
                        model.addElement(todosLosProductos.get(i));
                    }
                    
                    jcb_productos.setModel(model);
                    
                   // JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente!");
                    System.out.println("traje " + aA.getElementos().size());
                }// fin del ifjj

            } catch (Exception e) {
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CrearCliente;
    private javax.swing.JButton btn_guardarCajero;
    private javax.swing.JButton btn_productos;
    private javax.swing.JButton btn_productosAgregar;
    private javax.swing.JButton btn_realizarCompra;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcb_cajeros;
    private javax.swing.JComboBox<String> jcb_productos;
    private javax.swing.JTextField tf_edadCliente;
    private javax.swing.JTextField tf_nombreCajero;
    private javax.swing.JTextField tf_nombreCliente;
    private javax.swing.JTextField tf_nombreProductos;
    private javax.swing.JTextField tf_precioProducto;
    private javax.swing.JTextField tf_tiempoProducto;
    // End of variables declaration//GEN-END:variables

    ArrayList<cliente> clientes = new ArrayList();
    ArrayList<cajero> cajeros = new ArrayList();

    ArrayList<orden> ordenes = new ArrayList();
    int cont;

    ArrayList<Object> todo = new ArrayList();
    DefaultTableModel primerModelo;
    cliente actualCliente;
    ArrayList<producto> productos = new ArrayList();

    ArrayList<producto> todosLosProductos = new ArrayList();
}
